name: Deployment pipelin

on:
  push:
    branches:
      - main

jobs:
  preparacion_entorno:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: |
          echo "Hola Github Actions!!!"
      - name: Date
        run: |
          echo $(date)
      - name: List 
        run: |
          ls -l
