name: Deployment pipelin

on:
  push:
    branches:
      - main

jobs:
  preparacion_entorno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
        - name: Saludar
          run: |
            echo "Hola Github Actions!!!"
        - name: Date
          run: |
            echo $(date)
        - name: List 
          run: |
            ls -l
